package languagelab.mps.test.petrinetEdit.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptPetriNet = createDescriptorForPetriNet();
  /*package*/ final ConceptDescriptor myConceptPetrinetElement = createDescriptorForPetrinetElement();
  /*package*/ final ConceptDescriptor myConceptPetrinetIdentifier = createDescriptorForPetrinetIdentifier();
  /*package*/ final ConceptDescriptor myConceptPlace = createDescriptorForPlace();
  /*package*/ final ConceptDescriptor myConceptPlaceRef = createDescriptorForPlaceRef();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptPetriNet, myConceptPetrinetElement, myConceptPetrinetIdentifier, myConceptPlace, myConceptPlaceRef, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.PetriNet:
        return myConceptPetriNet;
      case LanguageConceptSwitch.PetrinetElement:
        return myConceptPetrinetElement;
      case LanguageConceptSwitch.PetrinetIdentifier:
        return myConceptPetrinetIdentifier;
      case LanguageConceptSwitch.Place:
        return myConceptPlace;
      case LanguageConceptSwitch.PlaceRef:
        return myConceptPlaceRef;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForPetriNet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.test.petrinetEdit", "PetriNet", 0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d494149L);
    b.class_(false, false, true);
    b.parent(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d49414cL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:06c89b7d-f025-4b09-af84-ac9e1baf5938(languagelab.mps.test.petrinetEdit.structure)/7219137829858263369");
    b.version(3);
    b.aggregate("elements", 0x7de7d34f3a7e11e2L).target(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d494294L).optional(true).ordered(true).multiple(true).origin("9072452311598371298").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPetrinetElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.test.petrinetEdit", "PetrinetElement", 0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d494294L);
    b.class_(false, false, false);
    b.parent(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d49414cL);
    b.origin("r:06c89b7d-f025-4b09-af84-ac9e1baf5938(languagelab.mps.test.petrinetEdit.structure)/7219137829858263700");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPetrinetIdentifier() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.test.petrinetEdit", "PetrinetIdentifier", 0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d49414cL);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:06c89b7d-f025-4b09-af84-ac9e1baf5938(languagelab.mps.test.petrinetEdit.structure)/7219137829858263372");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlace() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.test.petrinetEdit", "Place", 0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d494297L);
    b.class_(false, false, false);
    // extends: languagelab.mps.test.petrinetEdit.structure.PetrinetElement
    b.super_(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d494294L);
    b.origin("r:06c89b7d-f025-4b09-af84-ac9e1baf5938(languagelab.mps.test.petrinetEdit.structure)/7219137829858263703");
    b.version(3);
    b.property("tokens", 0x642f879b8d494298L).type(PrimitiveTypeId.INTEGER).origin("7219137829858263704").done();
    b.alias("place");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlaceRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.test.petrinetEdit", "PlaceRef", 0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d49429aL);
    b.class_(false, false, false);
    b.origin("r:06c89b7d-f025-4b09-af84-ac9e1baf5938(languagelab.mps.test.petrinetEdit.structure)/7219137829858263706");
    b.version(3);
    b.associate("target", 0x642f879b8d49429bL).target(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d494297L).optional(false).origin("7219137829858263707").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("languagelab.mps.test.petrinetEdit", "Transition", 0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d4942d9L);
    b.class_(false, false, false);
    // extends: languagelab.mps.test.petrinetEdit.structure.PetrinetElement
    b.super_(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d494294L);
    b.origin("r:06c89b7d-f025-4b09-af84-ac9e1baf5938(languagelab.mps.test.petrinetEdit.structure)/7219137829858263769");
    b.version(3);
    b.aggregate("input", 0x2955e5ac4e02fc90L).target(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d49429aL).optional(true).ordered(true).multiple(true).origin("2978539256781405328").done();
    b.aggregate("output", 0x2955e5ac4e02fc92L).target(0x7e0c4a2d8d374f16L, 0xac1d16d7be38f5eaL, 0x642f879b8d49429aL).optional(true).ordered(true).multiple(true).origin("2978539256781405330").done();
    b.alias("transition");
    return b.create();
  }
}
