package languagelab.mps.lang.text.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_WhiteSpaceRole extends EnumerationDescriptorBase {

  public EnumerationDescriptor_WhiteSpaceRole() {
    super(0x94b477d9e67c45feL, 0x813c26d61ae04a91L, 0x7b555f3bcc741247L, "WhiteSpaceRole", "r:e345bfe4-a7ce-41f2-aad2-23740a591142(languagelab.mps.lang.text.structure)/8887114150123409991");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember__0_0 = new EnumerationDescriptor.MemberDescriptor("_0", "empty", 0x7b555f3bcc741248L, "r:e345bfe4-a7ce-41f2-aad2-23740a591142(languagelab.mps.lang.text.structure)/8887114150123409992");
  private final EnumerationDescriptor.MemberDescriptor myMember__1_0 = new EnumerationDescriptor.MemberDescriptor("_1", "space", 0x7b555f3bcc741249L, "r:e345bfe4-a7ce-41f2-aad2-23740a591142(languagelab.mps.lang.text.structure)/8887114150123409993");
  private final EnumerationDescriptor.MemberDescriptor myMember__2_0 = new EnumerationDescriptor.MemberDescriptor("_2", "indent", 0x7b555f3bcc74124cL, "r:e345bfe4-a7ce-41f2-aad2-23740a591142(languagelab.mps.lang.text.structure)/8887114150123409996");
  private final EnumerationDescriptor.MemberDescriptor myMember__3_0 = new EnumerationDescriptor.MemberDescriptor("_3", "blockstart", 0x7b555f3bcc741250L, "r:e345bfe4-a7ce-41f2-aad2-23740a591142(languagelab.mps.lang.text.structure)/8887114150123410000");
  private final EnumerationDescriptor.MemberDescriptor myMember__4_0 = new EnumerationDescriptor.MemberDescriptor("_4", "blockend", 0x7b555f3bcc741255L, "r:e345bfe4-a7ce-41f2-aad2-23740a591142(languagelab.mps.lang.text.structure)/8887114150123410005");
  private final EnumerationDescriptor.MemberDescriptor myMember__5_0 = new EnumerationDescriptor.MemberDescriptor("_5", "statement", 0x7b555f3bcc74125bL, "r:e345bfe4-a7ce-41f2-aad2-23740a591142(languagelab.mps.lang.text.structure)/8887114150123410011");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x94b477d9e67c45feL, 0x813c26d61ae04a91L, 0x7b555f3bcc741247L, 0x7b555f3bcc741248L, 0x7b555f3bcc741249L, 0x7b555f3bcc74124cL, 0x7b555f3bcc741250L, 0x7b555f3bcc741255L, 0x7b555f3bcc74125bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember__0_0, myMember__1_0, myMember__2_0, myMember__3_0, myMember__4_0, myMember__5_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember__0_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "_0":
        return myMember__0_0;
      case "_1":
        return myMember__1_0;
      case "_2":
        return myMember__2_0;
      case "_3":
        return myMember__3_0;
      case "_4":
        return myMember__4_0;
      case "_5":
        return myMember__5_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
